utils/getFileIcon.ts
`m4a` is an MPEG 4 filename extension for audio.
https://en.wikipedia.org/wiki/MPEG-4_Part_14#Filename_extensions
=> Add icon for m4a audio files

pages/api/index.ts
The sensitive MS drive API can not handle trailing slash in the folder path.
Removing it fixes the index page 500 problem.
Closes #102
=> Fix index page 500 error

pages/api/index.ts
When listing root children, the path need to omit a colon
See https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_children?view=odsp-graph-online#list-children-in-the-root-of-the-current-users-drive
Close #124 , close #157
=> Fix 500 when setting root as public root

components/FileListing.tsx
As the near above code used `encodeURIComponent`, here it may need to add it too.
=> Add urlencoding for one filename

components/previews/PDFPreview.tsx
As mentioned in
https://github.com/wojtekmaj/react-pdf#support-for-non-latin-characters,
pdf.js needs the bundled cMaps files to work.
Fixes #75
=> fix(pdfpreview): Support for non-latin characters

components/FileListing.tsx, components/Navbar.tsx, package-lock.json, package.json, pages/[...path].tsx, pages/index.tsx, utils/tools.ts
The PR adds a new column (by moving `col-span-1` from filename column to the new column) to provide selection checkbox and download button to download selected files (excluding folders) in the current directory. The files will be compressed into one single zip file and then passed to browser to download. (In the process, data is stored in blobs so there should not be huge memory consumption, but I have not take a benchmark)
The reason why selecting folders is not implemented is that, while recursively go through the folders is difficult according to https://github.com/spencerwooo/onedrive-vercel-index/discussions/136#discussioncomment-1450067 , folders may be password-protected and it seems hard to find a proper way to ask users for the multiply passwords. Anyway, file selecting support …
=> Selecting to download support for current directory

components/FileListing.tsx, components/Loading.tsx, utils/tools.ts
~~As a draft, the PR adds some utilities for folder download, allowing one-shot access to recursive tree-like file metadata in the listing page.~~
Updated: The PR adds folder download support. It adds download buttons for folders in file listing page. By the download button, the folder can be downloaded as a zip with the same folder structure as it in OneDrive. It also provides utils for one-shot access to recursive tree-like file metadata.
Due to react hook limit (no conditional call or called in loop), this API does not reuse SWR cache (I tried still can not figure out how to, though SWR team is working on it), but fetches `/api` immediately and arranges the responses. It makes the API pretty slow (seconds for 3 level folder). However, if it is for user one-shot action like downloading …
=> Folder download

pages/api/index.ts
Closes #307
The PR adds `posixPath.normalize` to clean `path` param and make it absolute as long as it is ensured to be a string. It ensures `path` is *good* in the following process.
=> Clean path param earlier

components/FileListing.tsx, components/MultiFileDownloader.tsx
The PR adds code to ignore and skip 4xx errors when traversing. 4xx when traversing is either not setting password or `.password` file not found, which are safe to ignore and skip.
=> Error handling in traversing

components/FileListing.tsx, components/previews/DefaultPreview.tsx, pages/api/index.ts, types/index.d.ts, utils/getFileIcon.ts, utils/getPreviewType.ts
Closes #130
In the PR `getFileIcon` is modified and `getPreviewType` is added, who have 2nd optional arg to help to decide file type.
In `api/index` file and folder queries will select `video` attribute additionally, which will not be undefined if the file is a video.
One extra is `SearchModal`. Since OneDrive API can not perform `video` select in searching, file icons in it is kept unchanged. Though after users click the required result and go into the detail page, they will see the right icon.
The PR will make the app able to differ Typescript text files with Televison Stream video files. Though react-player does not seem to support ts videos and in the preview page the video does not play but just black the screen, it can avoid print unprintable characters in the preview box and inform …
=> Differ file types which have the same extensions

pages/api/name/[name].ts
Discussion #290
The PR adds a new api route `api/name/[name]`, which forwards the process to `api/index`, to allow users to set any value as the url final component, which is used as filename by services like Notion to define the file type.
To use it, modified `<...>/api?<...>` as `<...>/api/name/<filename>?<...>`.
=> Support custom url final component name for Notion

components/Navbar.tsx
Ref: discussion #346
Ctrl+K opens browser search box to search with default search engine in Chrome by default. The default behavior should be disabled since we use Ctrl+K to search in the app.
=> Avoid opening browser search box in Chrome when pressing Ctrl+K

components/FolderGridLayout.tsx, pages/api/index.ts, pages/api/thumbnail.ts
Ref: discussion #378
The PR adds a new API, `/api/thumbnail`, which redirects to the thumbnail url, to fix thumbnail fetching on OneDrive 世纪互联 which does not support `expand` thumbnails.
For authorization, since thumbnails are related to file content, the new API takes path as arg, and check if it is under any protected route. Currently protected pathes are simply rejected (because the url is passed directly to `<img>`, which can not customize headers). https://stackoverflow.com/questions/34096744/how-should-i-load-images-if-i-use-token-based-authentication may be a solution though I am not sure whether it is worthy.
=> Fix thumbnails under OneDrive 世纪互联

components/previews/DefaultPreview.tsx
`'Unavailable'` > `t('Unavailable')`
=> Fix "Unavailable" not translated at Hashes

components/FolderGridLayout.tsx, components/previews/AudioPreview.tsx, components/previews/VideoPreview.tsx, pages/api/index.ts, pages/api/thumbnail.ts, tailwind.config.js, types/index.d.ts
- This sacrifices thumbnail load time, but increases folder listing requests' performance. (As we are requesting fewer items from the OneDrive API on initial render.)
=> Thumbnails on demand

components/previews/MarkdownPreview.tsx
在文件夹展示 README 时，如果使用了相对路径的图片。
程序则会在当前路径的父路径寻找文件，导致图片加载失败。
按照逻辑，应当在当前路径寻找文件。
效果预览：[小林家的龙女仆S](https://drive.android99.me/zh-CN/🎬%20视频/小林家的龙女仆S/)
(不确定代码这样修改是否合适 \_(:з」∠)\_)
=> Fix relative path of readme image

components/MultiFileDownloader.tsx
The PR, other than using BFS, follows the top-down structure of the file tree, and uses `Promise.race` other than `Promise.all` to make the tree download theorically faster. Instead of layered fetching, whenever a folder is fetchable, it is added to the fetching pool, and the app waits any time point via `Promise.race`.
What is more, the PR handles pagination in the traversing. Now folders with tons of files should be correctly downloaded. However an integrated test for folder download with pagination has not been done. I would do the test shortly later.
=> Improve traversing concurrency and handle pagination

components/FileListing.tsx, components/FolderGridLayout.tsx, components/FolderListLayout.tsx
Ref: #305
The PR makes the app display filename always with its extension, even when the space is not enough. Ellipsis when overflowing will occurs at the end of the basename. Though someone can still not see the full filename on mobile devices, the extension may help to get information about the files.
DRAWBACK: When screen is resized, sometimes there will be a small gap between the ellipsis and extension, which looks a little strange.
=> Display extension still when space for filename is not enough

components/CustomEmbedLinkMenu.tsx, components/DownloadBtnGtoup.tsx, components/FileListing.tsx, components/FolderGridLayout.tsx, components/FolderListLayout.tsx, components/MultiFileDownloader.tsx, components/SearchModal.tsx, components/previews/AudioPreview.tsx, components/previews/CodePreview.tsx, components/previews/DefaultPreview.tsx, components/previews/EPUBPreview.tsx, components/previews/ImagePreview.tsx, components/previews/MarkdownPreview.tsx, components/previews/OfficePreview.tsx, components/previews/PDFPreview.tsx, components/previews/TextPreview.tsx, components/previews/URLPreview.tsx, components/previews/VideoPreview.tsx, config/api.config.js, pages/api/index.ts, pages/api/item.ts, pages/api/name/[name].ts, pages/api/raw.ts, pages/api/search.ts, pages/api/thumbnail.ts, pages/onedrive-vercel-index-oauth/step-2.tsx, types/index.d.ts, utils/fetchOnMount.ts, utils/fetchWithSWR.ts, utils/oAuthHandler.ts
=> Standalone raw file redirects

utils/getReadablePath.ts
Closes #464
The PR removes `+` out of the kept charset. For other kept chars `[*:@,!]` I have done tests on Chrome address bar to ensure it can auto-encode them correctly as even query params.
The PR also removes trailing handling which aims to fullfill autolink, since there may be other chars (not encoded, which is required by RFC) that can still break autolink.
=> Fix readable URL character filtering

components/CustomEmbedLinkMenu.tsx
The PR makes the default value of filename inputbox in custom link menu become the final component of the readable URL other than the original URL. The customized can still keep browser-level valid since the whole readable path is.
=> Make filename inputbox default value in custom link menu readable

components/CustomEmbedLinkMenu.tsx
remove redundant ending slash so that filename can be recognized.
For example: in `https://.../api/name/somevideo.mp4/?path=/somevideo.mp4`, the file name is not the final path, so it won't be recognized. Manually removing the ending slash (`https://.../api/name/somevideo.mp4?path=/somevideo.mp4`) fixes this problem (tested in notion).
=> fix filename not recognized in generated custom link

pages/api/index.ts
Closes #606
`data` of axios responses is JSON-parsed, which causes numeric password is unexpectedly recognized as integers.
=> Fix numeric password not working

utils/getFileIcon.ts
According to the description of [`@fortawesome/fontawesome-common-types`](https://www.npmjs.com/package/@fortawesome/fontawesome-common-types):
> If you are trying to import types from this package we highly recommend you do the following instead as all types in this package are re-exported to the main fontawesome package.
> ```js
> import { IconName } from `@fortawesome/fontawesome-svg-core`
> ```
Actually when building the project in a `node:18-alpine` Docker container, `next build` will complain the compiler SWC can not find types of `@fortawesome/fontawesome-common-types` and fails, but `@fortawesome/fontawesome-svg-core` will be OK. The PR may help users who want to build the project in a container to selfhost it.
=> Fix imports from `fontawesome-common-types` for clean build

components/SearchModal.tsx
According to
https://github.com/spencerwooo/onedrive-vercel-index/blob/152380bd057d256bcd6cf3ececefcf5826fecaf9/utils/fetchWithSWR.ts#L18-L20
When an error occurs from item API, as for the error reporting code
https://github.com/spencerwooo/onedrive-vercel-index/blob/152380bd057d256bcd6cf3ececefcf5826fecaf9/components/SearchModal.tsx#L116
here `error` is not a `string` but `{ status: number; message: any }`
Since the error object is passed into the sub component like
https://github.com/spencerwooo/onedrive-vercel-index/blob/152380bd057d256bcd6cf3ececefcf5826fecaf9/components/SearchModal.tsx#L121
And the `itemDescription` prop is directly used in `{}` like
https://github.com/spencerwooo/onedrive-vercel-index/blob/152380bd057d256bcd6cf3ececefcf5826fecaf9/components/SearchModal.tsx#L106-L108 …
=> Fix error report for search result item requests

components/previews/VideoPreview.tsx
related issues #611
discussions #579
This will allow video previews on iOS to use the system's full screen while taking advantage of iOS' picture-in-picture feature, as well as the ability to change the speed of video playback using the system player on iOS 15+.
However, subtitles will not be visible in full screen this way, even if the Show subtitles option is available and turned on in the system player.
But I think there are probably more people who need iOS full screen than subtitles, so maybe we need to find another way to fix the subtitle problem.😂
=> support ios safari fullscreen

src/components/previews/AudioPreview.tsx
=> Fix audio preview covers style when is not square

package.json, pnpm-lock.yaml, src/pages/_app.tsx
Added support for Vercel analytics by using [their package](https://www.npmjs.com/package/@vercel/analytics). This will allow users to track page views and other stats from their Vercel dashboard.
=> Vercel analytics support
